sudo: false

dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  include:
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: 5.4
    - php: 5.3
      dist: precise

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - |
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
        composer global require "phpunit/phpunit=6.5.*"
      elif [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then
        composer global require "phpunit/phpunit=5.7.*"
      else
        composer global require "phpunit/phpunit=4.8.*"
      fi
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install
